name = "sl"
type = "javascript"
account_id = "2fff71b39e84b0e09ab12a300f75ba73"
workers_dev = true
route = "sl"
zone_id = ""
kv_namespaces = [
  { binding = "sl", id = "KavcneogBEYMtlJN57ZSv2nIDsUbZQbrakkHWkpn", preview_id = "KavcneogBEYMtlJN57ZSv2nIDsUbZQbrakkHWkpn" }
]
